export enum ecircondecouverte {
  SYMPTOMATIQUE = 'SYMPTOMATIQUE',

  DIAGNOSTIC_PRENATAL = 'DIAGNOSTIC_PRENATAL',

  ENQUETE_FAMILIALE = 'ENQUETE_FAMILIALE',

  FORTUITE = 'FORTUITE',

  DEPISTAGE = 'DEPISTAGE',
}
