export enum edeficiencepsychiqueval {
  TROUBLES_COMMUNICATION_LANGUAGE = 'TROUBLES_COMMUNICATION_LANGUAGE',

  TROUBLES_COMPORTEMENT = 'TROUBLES_COMPORTEMENT',

  TROUBLES_HUMEUR = 'TROUBLES_HUMEUR',

  AUTRE = 'AUTRE',

  NP = 'NP',
}
