export enum elaboratoire {
  BIOCHIMIERABTA = 'BIOCHIMIERABTA',

  BIOCHIMIESOUSSE_FHACHED = 'BIOCHIMIESOUSSE_FHACHED',

  BIOCHIMIESFAX = 'BIOCHIMIESFAX',

  LABORATOIREPRIVE = 'LABORATOIREPRIVE',

  LABORATOIREETRANGER = 'LABORATOIREETRANGER',
}
