export enum emedicamentspecifiqueval {
  NTBC_NITISIN_ORFADIN = 'NTBC_NITISIN_ORFADIN',

  CITRATEDEBETAINE_CYSTADANE = 'CITRATEDEBETAINE_CYSTADANE',

  BH4DICHLORYDRATEDESAPROPTERINE_JUVAN = 'BH4DICHLORYDRATEDESAPROPTERINE_JUVAN',

  AUTRE = 'AUTRE',
}
