export enum ename {
  BRANDT = 'BRANDT',

  BARBER = 'BARBER',

  DNPH = 'DNPH',

  PHENISTIX = 'PHENISTIX',

  ALPHAFOETOPROTEINE = 'ALPHAFOETOPROTEINE',

  DOSAGEPHESURPAPIER = 'DOSAGEPHESURPAPIER',

  CAAPLASMATIQUE = 'CAAPLASMATIQUE',

  CAAURINAIRE = 'CAAURINAIRE',

  CAOURINAIRE = 'CAOURINAIRE',

  SUCCINYLACETONEURINAIRE = 'SUCCINYLACETONEURINAIRE',

  SUCCINYLACETONESURPAPIERGUTHRIE = 'SUCCINYLACETONESURPAPIERGUTHRIE',

  DOSAGEHOMOCYSTEINEPLASMATIQUE = 'DOSAGEHOMOCYSTEINEPLASMATIQUE',

  DOSAGEENZYMATIQUE = 'DOSAGEENZYMATIQUE',

  BIOLOGIEMOLECULAIRE = 'BIOLOGIEMOLECULAIRE',
}
