export enum esignesneurologiques {
  TROUBLES_DE_LA_CONSCIENCE = 'TROUBLES_DE_LA_CONSCIENCE',

  RETARD_PSYCHOMOTEUR = 'RETARD_PSYCHOMOTEUR',

  RETARD_MENTAL = 'RETARD_MENTAL',

  SIGNES_SPECTRE_AUTISTIQUE = 'SIGNES_SPECTRE_AUTISTIQUE',

  EPILEPSIE = 'EPILEPSIE',

  CRISE_PSEUDOPORPHYRIQUE = 'CRISE_PSEUDOPORPHYRIQUE',

  AUTRE = 'AUTRE',
}
