export enum evitamineval {
  VITAMINEB1_THIAMINE = 'VITAMINEB1_THIAMINE',

  VITAMINEB6_PYRIDOXINE = 'VITAMINEB6_PYRIDOXINE',

  VITAMINEB9_ACIDEFOLIQUE = 'VITAMINEB9_ACIDEFOLIQUE',

  VITAMINEB12_COBALAMINE = 'VITAMINEB12_COBALAMINE',

  VITAMINEC_ACIDEASCORBIQUE = 'VITAMINEC_ACIDEASCORBIQUE',

  NP = 'NP',
}
