import dayjs from 'dayjs/esm';
import { IPathologie } from 'app/entities/pathologie/pathologie.model';
import { esexe } from 'app/entities/enumerations/esexe.model';
import { estatut } from 'app/entities/enumerations/estatut.model';
import { ecirconstance } from 'app/entities/enumerations/ecirconstance.model';
import { elieudeces } from 'app/entities/enumerations/elieudeces.model';
import { econsanguinite } from 'app/entities/enumerations/econsanguinite.model';
import { egouvernorat } from 'app/entities/enumerations/egouvernorat.model';
import { egouvernoratmere } from 'app/entities/enumerations/egouvernoratmere.model';
import { ecouverture } from 'app/entities/enumerations/ecouverture.model';
import { eactivite } from 'app/entities/enumerations/eactivite.model';
import { escolarisetype } from 'app/entities/enumerations/escolarisetype.model';
import { eniveauscolarisation } from 'app/entities/enumerations/eniveauscolarisation.model';
import { ecasfamiliaux } from 'app/entities/enumerations/ecasfamiliaux.model';
import { edecesbasage } from 'app/entities/enumerations/edecesbasage.model';
import { ecircondecouverte } from 'app/entities/enumerations/ecircondecouverte.model';
import { eage_premier_symptome } from 'app/entities/enumerations/eage-premier-symptome.model';
import { eagepremiereconsultation } from 'app/entities/enumerations/eagepremiereconsultation.model';
import { ehandicapmental } from 'app/entities/enumerations/ehandicapmental.model';
import { eQI } from 'app/entities/enumerations/e-qi.model';
import { eMoteur } from 'app/entities/enumerations/e-moteur.model';
import { egrade } from 'app/entities/enumerations/egrade.model';
import { edeficitneuro } from 'app/entities/enumerations/edeficitneuro.model';
import { edeficitneurosensorielval } from 'app/entities/enumerations/edeficitneurosensorielval.model';
import { edeficiencepsychique } from 'app/entities/enumerations/edeficiencepsychique.model';
import { edeficiencepsychiqueval } from 'app/entities/enumerations/edeficiencepsychiqueval.model';
import { eregime } from 'app/entities/enumerations/eregime.model';
import { eregimeval } from 'app/entities/enumerations/eregimeval.model';
import { emedicamentspecifique } from 'app/entities/enumerations/emedicamentspecifique.model';
import { emedicamentspecifiqueval } from 'app/entities/enumerations/emedicamentspecifiqueval.model';
import { evitamines } from 'app/entities/enumerations/evitamines.model';
import { evitamineval } from 'app/entities/enumerations/evitamineval.model';
import { egreffehepatique } from 'app/entities/enumerations/egreffehepatique.model';
import { erededucationfonctionnelle } from 'app/entities/enumerations/erededucationfonctionnelle.model';
import { eappareillage } from 'app/entities/enumerations/eappareillage.model';
import { epsychologie } from 'app/entities/enumerations/epsychologie.model';
import { eergotherapie } from 'app/entities/enumerations/eergotherapie.model';
import { edepistage_post_natal_oriente } from 'app/entities/enumerations/edepistage-post-natal-oriente.model';
import { eechelledepistage } from 'app/entities/enumerations/eechelledepistage.model';
import { enouveaux_cas_depistes } from 'app/entities/enumerations/enouveaux-cas-depistes.model';
import { elienparente1 } from 'app/entities/enumerations/elienparente-1.model';
import { elienparente2 } from 'app/entities/enumerations/elienparente-2.model';
import { ICasconfirme } from '../casconfirme/casconfirme.model';

export interface IFiche {
  id: number;
  datemaj?: dayjs.Dayjs | null;
  type_observation?: string | null;
  identifiant_registre?: string | null;
  date_enregistrement?: dayjs.Dayjs | null;
  sexe?: esexe | null;
  date_naissance?: dayjs.Dayjs | null;
  statut?: estatut | null;
  date_deces?: dayjs.Dayjs | null;
  circonstance_deces?: ecirconstance | null;
  autre_circonstance_deces?: string | null;
  lieu_deces?: elieudeces | null;
  consanguinite?: econsanguinite | null;
  origine_geo_pere_gouvernorat?: egouvernorat | null;
  origine_geo_mere_gouvernorat?: egouvernoratmere | null;
  origine_geo_pere_deleguation?: string | null;
  origine_geo_mere_deleguation?: string | null;
  couverture_sociale?: ecouverture | null;
  autre_couverture_sociale?: string | null;
  activite?: eactivite | null;
  btravail?: boolean | null;
  travail?: string | null;
  scolarise?: boolean | null;
  type_scolarise?: escolarisetype | null;
  niveau_scolarisation?: eniveauscolarisation | null;
  cas_familiaux?: ecasfamiliaux | null;
  nbcasconfirme?: number | null;
  nbcassuspectes?: number | null;
  nbcasdecedes?: number | null;
  deces_en_bas_age?: edecesbasage | null;
  nbcas_deces_age_bas?: number | null;
  circonstances_decouverte?: ecircondecouverte | null;
  age_aux_premiers_symptomes?: eage_premier_symptome | null;
  an_age_premiers_symptomes?: number | null;
  mois_age_premiers_symptomes?: number | null;
  jours_premiers_symptomes?: number | null;
  age_premiere_consultation?: eagepremiereconsultation | null;
  an_age_premiere_consultation?: number | null;
  mois_age_premiere_consultation?: number | null;
  jours_premiere_consultation?: number | null;
  date_derniere_evaluation?: dayjs.Dayjs | null;
  date_diagnostic?: dayjs.Dayjs | null;
  handicap_mental?: ehandicapmental | null;
  qi?: eQI | null;
  handicap_moteur?: eMoteur | null;
  hadicap_moteur_grade?: egrade | null;
  deficit_neurosensoriel?: edeficitneuro | null;
  deficit_neurosensoriel_val?: edeficitneurosensorielval | null;
  deficience_psychique?: edeficiencepsychique | null;
  deficience_psychique_val?: edeficiencepsychiqueval | null;
  autre_deficience_psychique?: string | null;
  regime?: eregime | null;
  regime_val?: eregimeval | null;
  medicament_specifique?: emedicamentspecifique | null;
  medicament_specifique_val?: emedicamentspecifiqueval | null;
  autre_medicament_specifique?: string | null;
  vitamines?: evitamines | null;
  vitamines_val?: evitamineval | null;
  greffehepatique?: egreffehepatique | null;
  reeducation_fonctionnelle?: erededucationfonctionnelle | null;
  appareillage?: eappareillage | null;
  psuchologie?: epsychologie | null;
  ergotherapie?: eergotherapie | null;
  depistage_post_natal_oriente?: edepistage_post_natal_oriente | null;
  echelle_depistage?: eechelledepistage | null;
  nombre_individus_depistes?: number | null;
  nouveaux_cas_depistes?: enouveaux_cas_depistes | null;
  nombre_nouveaux_cas_depistes?: number | null;
  code_registre1_cas_depistes?: string | null;
  lien_parente1_cas_depistes?: elienparente1 | null;
  autre_lien_parente1?: string | null;
  code_registre2_cas_depistes?: string | null;
  lien_parente2_cas_depistes?: elienparente2 | null;
  autre_lien_parente2?: string | null;
  nombre_de_grossesse_ulterieures?: number | null;
  nomre_DPN?: number | null;
  nombre_nouveaux_cas_diagnostiques?: number | null;
  nombre_ITG?: number | null;
  nomre_de_grossesses_poursuivies?: number | null;
  nombre_de_foetus_sains?: number | null;
  pathologie?: Pick<IPathologie, 'id'> | null;

  casconfirmes?: ICasconfirme[] | null; //  relation OneToMany
}

export type NewFiche = Omit<IFiche, 'id'> & { id: null };
